# Generated by Django 4.2.9 on 2026-03-07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('monthly_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=60)),
                ('insight_key', models.CharField(max_length=120)),
                ('is_useful', models.BooleanField(blank=True, null=True)),
                ('corrected_value', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_feedback', to='api.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialgoal',
            index=models.Index(fields=['user', 'is_active'], name='financial_g_user_id_1bf197_idx'),
        ),
        migrations.AddIndex(
            model_name='insightfeedback',
            index=models.Index(fields=['insight_type', 'created_at'], name='insight_fee_insight_b52fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='insightfeedback',
            index=models.Index(fields=['user', 'created_at'], name='insight_fee_user_id_8602a1_idx'),
        ),
    ]
