# Generated by Django 4.2.9 on 2026-03-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('draft_name', models.CharField(blank=True, help_text='Optional name for the draft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expense_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='budgets_departm_bef89a_idx',
            old_name='budgets_depa_departm_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='budgets_categor_803a86_idx',
            old_name='budgets_categ_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_user_id_ea4a72_idx',
            old_name='notificatio_user_id_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_notific_e0b12c_idx',
            old_name='notificatio_notific_created_idx',
        ),
        migrations.AddField(
            model_name='expensedraft',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AddField(
            model_name='expensedraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expensedraft',
            index=models.Index(fields=['user', '-updated_at'], name='expense_dra_user_id_7d15fd_idx'),
        ),
    ]
