# Generated by Django 4.2.9 on 2026-03-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_expense_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SmartSpend', max_length=120)),
                ('default_currency', models.CharField(default='INR', max_length=3)),
                ('budget_alert_threshold', models.IntegerField(default=80, help_text='Global budget alert threshold (%)')),
                ('email_notifications', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
    ]
