# Generated by Django 4.2.9 on 2026-03-11 02:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_admin_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='auto_approve_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='notification_refresh_minutes',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='adminsetting',
            name='require_receipt_above',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
